import "bootstrap/dist/css/bootstrap.min.css";
import Styles from "./layout.module.css";
import NavbarPublic from "../../component/NavbarPublic";
import Footer from "../../component/Footer";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
export const metadata = {
  title: "Nabanna-App",
  description: "Generated by create next app",
};

export default function PublicLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${Styles.homeLayout} w-full`}>
        <div className={Styles.header}>{<NavbarPublic />}</div>
        <div className={Styles.main}>
          {children}
          <ToastContainer position="top-right" autoClose={3000} newestOnTop />
        </div>
        <div className={Styles.footer}>{<Footer />}</div>
      </body>
    </html>
  );
}
