// ✅ ADDED: All stylesNet in one place
export const styles = {
  formContainer: {
    width: "100%",
    maxWidth: "580px",
  },
  label: {
    display: "block",
    marginBottom: "8px",
    fontWeight: 600,
    fontSize: "0.875rem",
    color: "#374151",
    fontFamily: "'Inter', sans-serif",
    letterSpacing: "0.01em",
  },
  inputField: {
    width: "100%",
    "& .MuiOutlinedInput-root": {
      borderRadius: "10px",
      backgroundColor: "#fff",
      fontSize: "0.9rem",
      transition: "all 0.2s ease",
      "& fieldset": { borderColor: "#d1d5db", borderWidth: "1.5px" },
      "&:hover fieldset": { borderColor: "#9ca3af" },
      "&.Mui-focused fieldset": { borderColor: "#667eea", borderWidth: "2px" },
    },
    "& .MuiInputLabel-root": { fontSize: "0.875rem", color: "#6b7280" },
    "& .MuiInputLabel-root.Mui-focused": { color: "#667eea" },
  },
  radioGroup: {
    display: "flex",
    gap: "10px",
    flexWrap: "wrap",
    "& .MuiFormControlLabel-root": {
      backgroundColor: "#fff",
      border: "1.5px solid #e5e7eb",
      borderRadius: "10px",
      padding: "8px 16px",
      marginRight: 0,
      transition: "all 0.2s ease",
      "&:hover": { borderColor: "#667eea", backgroundColor: "#f8f7ff" },
    },
    "& .MuiRadio-root": {
      padding: "4px",
      "&.Mui-checked": { color: "#667eea" },
    },
    "& .MuiTypography-root": {
      fontSize: "0.875rem",
      fontWeight: 500,
      color: "#374151",
    },
  },
  errorText: {
    color: "#ef4444",
    fontSize: "0.75rem",
    marginTop: "4px",
    fontWeight: 500,
    fontFamily: "'Inter', sans-serif",
  },
  submitButton: {
    width: "100%",
    padding: "12px",
    borderRadius: "10px",
    fontSize: "0.95rem",
    fontWeight: 600,
    fontFamily: "'Inter', sans-serif",
    textTransform: "none",
    background: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
    color: "#fff",
    boxShadow: "0 4px 15px rgba(102, 126, 234, 0.4)",
    transition: "all 0.3s ease",
    "&:hover": {
      background: "linear-gradient(135deg, #5a6fd6 0%, #6a4292 100%)",
      boxShadow: "0 6px 20px rgba(102, 126, 234, 0.5)",
      transform: "translateY(-1px)",
    },
    "&:active": { transform: "translateY(0)" },
    "&.Mui-disabled": {
      background: "#e5e7eb",
      color: "#9ca3af",
      boxShadow: "none",
      transform: "none",
    },
  },
};